const history = {
  heading1: "GIDROGEOLOGIYA VA MUHANDISLIK GEOLOGIYA ",
  heading2: "INSTITUTI TARIXI",
  paragraph1:
    "1937-yilda O‘zSSR FA Geologiya instituti Gidrogeologiya va muhandislik geologiyasi bo‘limi bilan birgalikda tashkil etildi. M.M.Krylov, G.A.Mavlyanov rahbarligida B.I.Georgievskiy, A.F.Slyadnev, B.A.Beder, A.I.Shevchenko, N.N.Xodjiboyev, 1956 yildan A.S.Hasanov faoliyat yuritganlar. O‘sha yillarda institutning ko‘plab mutaxassislari respublikamizning turli sohadagi korxonalarida, oliy o‘quv yurtlarida ishladilar, jumladan: O`rtaosiyorangmetrazvedkada (Toshkent sh.) - L.Sandomirskiy, N.I.Plotnikov, M.V.Syrvatko va boshqalar, Ko`mir-razvedkada, O`ODUda‣ (O`zbekiston Milliy Universiteti)- N.I.Krylov, A.A.Xudoybergenov, R.V.Borodin va boshqalar, O`rOsPIda (ToshPI) -V.L.Dmitriev, G.A.Mavlyanov, ToshMTIda - F.I.Voronov, TIQXMMIda – D.M.Kats, gidrogeologik ekspeditsiyasida, keyinchalik O`zbekiston gidrogeologiya trestida – V.M.Fomin, V.N.Tolokonnikov, R.Ya. – Boyko, V.A.Geynts, V.P.Volkov va ko`plab boshqalar. Lekin turli ilmiy va ishlab chiqarish masalalari muhokama qilinadigan gidrogeologiya va muhandislik geologiyasining markazi OʻzSSR FA Geologiya institutining Gidrogeologiya va muhandislik geologiyasi boʻlimi edi. Geologiya institutining tashkil etilgan davri O‘zbekistonda irrigatsiya qurilishi keng ko‘lamli bo‘lgan davrga to‘g‘ri keldi. Shu munosabat bilan respublikada irrigatsiyani rivojlantirish, Och, Qarshi dashtlari, Amudaryoning quyi oqimi hamda boshqa yerlarida sugʻoriladigan va yangi oʻzlashtiriladigan maydonlarni kengaytirish rejalari ishlab chiqilgan boʻlib, ular suv xo‘jaligining ulkan tadbirlarida, sug‘oriladigan maydonlarni kengaytirishda o‘z ifodasini topdi. Shu munosabat bilan gidrogeologiya va muhandislik geologiyasi kafedrasining asosiy ilmiy tadqiqot ishlari sug‘oriladigan yerlarning melioratsiya holatini rivojlantirishga qaratildi. Institut gidrogeologik va muhandislik-geologik tadqiqotlarning ikkita asosiy yo‘nalishiga asos soldi.",
  paragraph2: `Geologiya institutining tashkil etilgan davri O‘zbekistonda irrigatsiya qurilishi keng ko‘lamli bo‘lgan davrga to‘g‘ri keldi. Shu munosabat bilan respublikada irrigatsiyani rivojlantirish, Och, Qarshi dashtlari, Amudaryoning quyi oqimi hamda boshqa yerlarida sugʻoriladigan va yangi oʻzlashtiriladigan maydonlarni kengaytirish rejalari ishlab chiqilgan boʻlib, ular suv xo‘jaligining ulkan tadbirlarida, sug‘oriladigan maydonlarni kengaytirishda o‘z ifodasini topdi. Shu munosabat bilan gidrogeologiya va muhandislik geologiyasi kafedrasining asosiy ilmiy tadqiqot ishlari sug‘oriladigan yerlarning melioratsiya holatini rivojlantirishga qaratildi. Institut gidrogeologik va muhandislik-geologik tadqiqotlarning ikkita asosiy yo‘nalishiga asos soldi.`,
  paragraph3: `Birinchisi, irrigatsiya dehqonchiligi ehtiyojlaridan kelib chiqib gidrogeologik va muhandislik-geologik rayonlashtirishni rivojlantirish. Bu yoʻnalishda Fargʻona vodiysi, Och dasht, Amudaryoning quyi oqimi, Buxoro vohasi va respublika sugʻorma dehqonchiligining boshqa hududlarida ilmiy-tadqiqot ishlari olib borildi.
  Mintaqalashtirishni rivojlantirishda O.K.Lange, M.A.Shmidt, B.M.Georgievskiy, G.A.Mavlyanov, M.M.Krilov va boshqalar qatnashdilar. 1928-1930 yillarda. O.K.Lange rahbarligida Farg‘ona vodiysida olib borilgan tadqiqotlar natijasida yer osti suvlari va minerallashuv chuqurligining birinchi xaritasi tuzildi. Gidrogeologiya boʻyicha birinchi ishlar, xususan, gidrogeologik xaritalarni tuzish metodikasi boʻyicha paydo boʻldi, bu esa gidrogeologik rayonlashtirishning boshlanishi boʻlib xizmat qildi hamda Geologiya instituti (N.A.Kenesarin, M.M.Krilov) uchun muhim yoʻnalishlardan biriga aylandi. Oʻzbekistonda (Och dasht) yer osti suvlari chuqurligi va gidro-izogipslarining birinchi xaritasi 1926-1928 yillarda 10 verst masshtabda tuzilgan.
`,
  paragraph4: `Gidrogeologik va muhandislik-geologik tadqiqotlarning tez va chuqur taraqqiyotga erishgan ikkinchi yoʻnalishi sugʻoriladigan yerlardagi yer osti suvlarining rejimi va balansini oʻrganish boʻlib, tuproq shoʻrlanishiga qarshi kurashish boʻyicha meliorativ tadbirlarni asoslashdan iborat edi. Avvalgi tadqiqotlar shuni ko‘rsatdiki, yerlarni sug‘orish natijasida yer osti suvlari sathi tezda tanqidiy (kritik) chuqurlikdan yuqoriga ko‘tarilib, yer sho‘rlanishga uchraydi. “Yer osti suvlarining tanqidiy (kritik) chuqurligi” atamasi fanga M.M.Krilov tomonidan kiritilgan va Oʻzbekiston hududi uchun 3,5 m boʻlib, undan yuqorida yerning shoʻrlanish jarayoni boshlanadi. Shu munosabat bilan O‘zbekistonning eng yaxshi va istiqbolli hududlaridan biri bo‘lgan Och dashtda yer osti suvlari balansining rejimi va dinamikasi atroflicha o‘rganildi. Funt suv rejimini sun'iy tartibga solish uchun sug'oriladigan yerlarning differensial meliorativ tadbirlarini o'tkazish zarurati belgilandi. Sug‘oriladigan yerlarda drenajlarni qurish to‘g‘risida savol tug‘ildi, uning ilmiy asoslangan yechimiga faqat rejim va muvozanatni o‘rganish orqali erishish mumkin edi. (M.M.Krylov, A.F.Slyadnev, N.N.Xodjiboyev, A.S.Hasanov). Geologiya institutining yer osti suvlarini oʻrganish boʻyicha ilmiy tadqiqotining ikki yoʻnalishi Oʻzbekistonda gidrogeologiya fanida yangi yoʻnalish – meliorativ gidrogeologiyaning vujudga kelishiga asos boʻldi. Yerni qayta ishlash va ularning holatini yaxshilashga yangi yondashuv amalda shakllantirildi.`,
  paragraph5: `Gidrogeologiya va muhandislik geologiyasi kafedrasi olimlari jamoasining ko‘p yillik izlanishlari natijasida meliorativ gidrogeologiyaning eng muhim va ustuvor vazifalari belgilab olindi:`,
  tasks1: `1. O‘zbekistonni gidrogeologik va meliorativ rayonlashtirish irrigatsiya va iqtisodiy rejalashtirishning asosi sifatida hamda mavjud va istiqbolli sug‘orish maydonlarini gidromodulli rayonlashtirish.`,
  tasks2: `2. Sug'orish tizimlarini boshqarishda meliorativ nazorat va gidrogeologik axborot xizmati uchun yer osti suvlari rejimining genetik turlari tasnifini ishlab chiqish.`,
  tasks3: `3. Melioratsiya tadbirlarining samaradorligini baholash va ularni loyihalashni asoslash, shuningdek, yer osti suvlari rejimini bashorat qilish uchun mavjud va istiqbolli sug‘orish tizimlari maydonlarining suv va suv-sho\`rlanish balansini o‘rganish.`,
  tasks4: `4. Meliorativ tadbirlarni loyihalashda zarur bo'lgan yer osti suvlari rejimini bashorat qilish usullarini ishlab chiqish, xususan, yer osti suvlarini, ayniqsa sho'rlanishga moyil bo'lgan yerlarda sun'iy tartibga solish uchun drenaj qurilmalarini ishlab chiqish.`,
  tasks5: `5. Sug'orishning qo'shimcha manbai sifatidagi yer osti suvlari zahiralarini baholash va ulardan foydalanish yo'llari.`,
  tasks6: `6. Vertikal va gorizontal drenaj va uning inshootlaridan foydalanish uchun geologik va gidrogeologik sharoitlarni aniqlash, shuningdek uni loyihalash uchun zarur parametrlarni aniqlash;`,
  paragraph6: `1960 yilgacha bu tadqiqotlar M.A.Shmidt, B.M.Georgiyevskiy, N.A.Kenesarin, M.M.Krilov, A.F.Slyadnev, A.I.Shevchenko, D.M.Kats, N.N.Xojibaev, A.S.Xasanov, S.Sh.Mirzaev, A.N.Sultanxodjayev va boshqalar tomonidan olib borilgan.`,
  paragraph7: `1960 yilgacha bu tadqiqotlar M.A.Shmidt, B.M.Georgiyevskiy, N.A.Kenesarin, M.M.Krilov, A.F.Slyadnev, A.I.Shevchenko, D.M.Kats, N.N.Xojibaev, A.S.Xasanov, S.Sh.Mirzaev, A.N.Sultanxodjayev va boshqalar tomonidan olib borilgan.
  OʻzSSR Vazirlar Kengashining 1959-yil 29-sentabrdagi 737-sonli “Oʻzbekiston Fanlar akademiyasi tizimi tarkibida Gidrogeologiya va muhandislik geologiyasi instituti (GIDROINGEO) tashkil etish toʻgʻrisida”gi qarori asosida 1960 yilning yanvarida GIDROINGEO instituti tashkil etilgan. Bu esa O‘zbekiston gidrogeologlari va muhandis-geologlarining katta jamoasi uchun muhim voqea bo‘ldi. Institutning birinchi rahbarlari: direktor – geologiya-mineralogiya fanlari doktori, professor G.A.Mavlyanov, fan bo‘yicha direktor o‘rinbosari – geologiya-mineralogiya fanlari nomzodi N.A.Kenesarin bo\`lgan.
`,
  paragraph8: `Institut tarkibi toʻrtta laboratoriya (mintaqaviy gidrogeologiya, mineral suvlar va gidrokimyo, meliorativ gidrogeologiya, muhandislik geologiyasi) hamda Golodnostepskaya gidrogeologik tadqiqot stansiyasidan tashkil topgan edi. Institut xodimlari esa 63 nafar bo\`lib, ulardan ikki nafar fan doktori va to‘rt nafar nomzoddan iborat bo\`lgan.
	Institut ilmiy-tadqiqot ishlarining asosiy yo‘nalishlari quyidagicha belgilab olingan edi: yer osti suvlarining hosil bo‘lish qonuniyatlarini o‘rganish, xalq xo‘jaligida foydalanish uchun yer osti suv resurslari va sanoat sho‘r suvini aniqlash, sug'oriladigan dehqonchilik maydonlarining meliorativ gidrogeologiyasining asosiy masalalarini ishlab chiqish; lyoss jinslarning qonuniyatlarini va ularning muhandislik-geologik xususiyatlarini o'rganish; gidrogeologik ishlarning usullari va texnikasini takomillashtirish, ularning tejamkorligi va samaradorligini tahlil qilish; gidrogeologik va muhandislik-geologik tadqiqotlarni ilmiy asoslash; ishlab chiqarish tashkilotlari tomonidan xalq xo‘jaligi masalalarini tezkor hal etish bo‘yicha individual amaliy takliflar ishlab chiqish; qurg'oqchil zona gidrogeologiyasi va muhandislik geologiyasi bo'yicha ilmiy-tadqiqot va tematik ishlarni muvofiqlashtirish.
`,
  paragraph9: `1961 yilda institutda yettita laboratoriya mavjud edi: yer osti suvlari resurslari, meliorativ gidrogeologiya, muhandislik geologiya, ko\`chki jarayonlari va hodisalari, mintaqaviy gidrogeologiya, kimyoviy – aniqlash laboratoriyalari hamda Golodnostepskaya gidrogeologik tadqiqot stantsiyasi. 1963 yilda institut SSSR Geologiya vazirligi tizimiga o'tkazildi. G.A.Mavlyanov Oʻzbekiston SSR Fanlar akademiyasi Prezidiumi Yer fani boʻlimi raisi, N.A.Kenesarin mudir, A.I.Islomov fan boʻyicha oʻrinbosari, V.A.Borisov ilmiy kotib etib tayinlanadi. O'sha paytda institutda 223 kishi ishlagan, shundan ikki nafari fan doktori, 18 nafari fan nomzodi edi. 1967-yilda institut O‘zbekiston SSR Geologiya vazirligi tizimiga o‘tkazilib, N.N.Xodjiboyev direktor, A.I.Islomov, keyinroq V.A.Geynts, fan bo‘yicha direktor o‘rinbosari, V.A.Borisov ilmiy kotib bo‘ldi.`,
  paragraph10: `1971 yil 4 iyunda GIDROINGEO instituti va “Oʻzbekgidrogeologiya” tresti negizida “Oʻzbekgidrogeologiya” ilmiy-ishlab chiqarish birlashmasi tashkil etildi. Institut kengayib, unda 26 ta laboratoriyaga ega 9 ta bo\`lim, tajribaviy - uslub partiyasi, ekspertiza partiyasi, malaka oshirish kurslari mavjud edi. Xodimlar soni 385 kishiga oshdi, shu jumladan. besh nafar fan doktori va 54 nafar fan nomzodi bor edi. Quyidagi bo\`limlar faoliyat yuritar edi: mintaqaviy gidrogeologiya va muhandislik-geologik tadqiqotlar bo\`limi, yer osti suvlarini qidirish va muhofaza qilish usullari bo\`limi, noosferaning gidrogeologiyasi bo\`lim, chuqur suvlar bo\`lim, muhandislik geodinamikasi bo\`limi, gidrogeologik jarayonlarni modellashtirish bo\`limi va h.k.). `,
  paragraph11: `Birlashma ekspeditsiyasida dala ishlariga chiqsh tashkil etilib, kursantlar ekspeditsiyalarning dala ishlari bilan yaqindan tanishardilar. Ularning xohishiga ko‘ra Samarqand, Qo‘qon, Buxoro va Xiva shaharlariga turistik ekskursiyalar uyushtirilardi. Kurslarga Sibir, Uzoq Sharq, Ukraina, Boltiqbo'yi davlatlari va boshqa mintaqalardan tashrif buyurishar edi. GIDROINGEO instituti qurg'oqchil zonada gidrogeologik va muhandislik-geologik tadqiqotlar uchun uslubiy rahbarlik qildi.`,
  paragraph12: `Uning negizida doktorlik va nomzodlik dissertatsiyalarini himoya qilish bo‘yicha maxsus Kengash tashkil etildi. Ushbu Kengashda 150 dan ortiq dissertatsiyalar himoya qilingan.`,
  paragraph13: `O\`zbekiston Respublikasi Prezidentining PQ 568 – sonli “Geologiya ishlarini tashkil etish va O‘zbekiston Respublikasi Davlat Geologiya va mineral resurslar qo‘mitasi faoliyatini takomillashtirish chora-tadbirlari to‘g‘risida” gi qarori hamda O\`zbekiston Respublikasi Davlat Geologiya va mineral resurslar qo\`mitasining 2007 yil 25-yanvardagi 11-sonli qaroriga binoan Institut Oʻzbekiston Respublikasi Davlat Geologiya va mineral resurslar qoʻmitasining tarkibiy boʻlinmasi hisoblanadi.`,
  directions: `Bugungi kunga qadar institut quyidagi yo‘nalishlarda ish olib bormoqda:`,
  directions1: `- Yer osti suvlari zahiralarini qidirish, razvedka qilish va baholash, yer osti suvlarini kamayishdan himoya qilish va ulardan oqilona foydalanish, hududiy gidrogeologik tadqiqotlarni ilmiy-uslubiy ta’minlash.`,
  directions2: `- Xavfli geologik jarayonlarning paydo bo'lishining oldini olish va bashorat qilish, qattiq foydali qazilmalar konlari va boshqa muhandislik-texnik obyektlarni qazib olishning barqarorligini asoslash.`,
  directions3: `- Mintaqaning hozirgi holatini baholash va ekologik vaziyatni yaxshilash maqsadida geologik muhitning tabiiy va texnogen omillar ta'sirida rivojlanishining geoekologik tadqiqotlari va xaritalarini tuzish, qonuniyatlari va bashoratlarini aniqlash.`,
  directions4: `- Mineral va sanoat yer osti suvlaridan balneologik maqsadlarda foydalanish va sanoat qimmatli komponentlarini qazib olish istiqbollarini baholash va bashorat qilish. Natijalar samaradorligini va ishonchliligini oshirishga imkon beradigan ilmiy-tadqiqot ishlarining ilmiy-texnik bazasini ta'minlash va takomillashtirish:
  gidrogeofizika, yerni masofadan zondlash, QGT texnologiyalari, ishlanmalar, matematik modellashtirish.
`,
  directions5: `- Davlat kadastrlarini yuritish: O‘zbekiston Respublikasining suv (yer osti suvlari bo‘yicha), muhofaza etiladigan tabiiy hududlari (MTH) va xavfli geologik jarayonlar (XGJ).
  Bugungi kunda institutda 181 nafar xodim, jumladan, 5 nafar fan doktori, 22 nafar fan nomzodi va 112 nafar oliy ma’lumotli mutaxassis mehnat qilmoqda.
`,
};

export default history;
