const production = {
   heading: "Ishlab chiqarish faoliyati",
   list_name: "Institut qquyidagilarni amalga oshiradi:",
   list_item1: "suv manbaalarini o’rganish va ulardan foydalanish;",
   list_item2: "gidromineral manbaalarini o’rganish va ulardan foydalanish;",
   list_item3: "meliorativ gidrogeologiya sohasida izlanishlar olib borish;",
   list_item4: "yer osti suvlarini monitoring qilish;",
   list_item5: "suv zahiralarining ifloslanishi va kamayish jarayonlarini o'rganish;",
   list_item6: "muhandislik geodinamikasi sohasidagi izlanishlar;",
   list_item7: "foydali qazilmalar konlarining gidrogeologik va muhandislik-geologik sharoitlarini o‘rganish;",
   list_item8: "shaharlar va sanoat hududlarining ekologik sharoitlarini o'rganish;",
   list_item9: "yangi texnik vositalarni ishlab chiqish;",
   list_item10: "yer osti suvlarini qidirish texnologiyalarini ishlab chiqish va ulardan oqilona foydalanish;",
   list_item11: "chuchuk yer osti suvlari zahiralarini sun’iy ravishda to‘ldirish va ularni ifloslanishdan himoya qilish texnologiyalarini ishlab chiqish;",
   list_item12: "gidromineral xom ashyoni qayta ishlash va ulardan foydalanish texnologiyalarini ishlab chiqish;",
   list_item13: "tog’ jinslarining fizik-mexanik xususiyatlarini aniqlash;",
   list_item14: "topografik-geodeziya ishlarini olib borish va xaritalar chiqarish;",
   list_item15: "qurilish va kapital ta’mirlash;",
   list_item16: "yiridik va jismoniy shaxslarga xizmat ko’rsatish;",
   list_item17: "qishloq xo'jaligi uchun o'g'itlar ishlab chiqarish;",
   list_item18: "qishloq xo'jaligi mahsulotlarini etishtirish;",
   list_item19: "mineral va ichimlik suvlarini quyish;",
   list_item20: "monografiyalar, to'plamlar, tavsiyalar, yo’riqnomalar, maqolalar, reklama maqolalari va boshqa nashrlarni chop etish;",
   list_item21: "O‘zbekiston va xorijiy davlatlarning tashkilot, muassasa, korxona va idoralari bilan hamkorlik qilish;",
   list_item22: "doktorantura, aspirantura va daraja oluvchilik orqali ilmiy xodimlarni tayyorlash;",
   list_item23: "malaka oshirish kurslarida oqish;",
   list_item24: "o'quv bo'limlari filiallarini ochish va oliy o'quv yurtlari talabalarini tayyorlash.",
   paragraph: "Institut litsenziyalar asosida faoliyatning boshqa turlari bilan shug‘ullanishi mumkin",
}

export default production