const scientific = {
   heading: "Ilmiy faoliyat",
   list1_name: "Institutning asosiy tadqiqot yo’nalishlari:",
   list1_item1: "Respublikaning gidromineral salohiyatini baholash, qidiruv ishlarini tashkil etish uchun bashoratlangan manbalarini baholagan holda yer osti suvlarini taqsimlash uchun istiqbolli maydonlarni ajratishni ilmiy-tadqiqot, geoekologik, tematik ishlar va laborator-texnologik tadqiqotlarning ustuvor yo‘nalishlarini asoslash va amalga oshirish;",
   list1_item2: "yer osti suvlari konlarini bashoratlash, qidirish, baholash va razvedka qilish usullarini takomillashtirish;",
   list1_item3: "tasdiqlangan geologiya-qidiruv dasturlari doirasida yer osti suvlari uchun geologiya-qidiruv ishlarini yo‘lga qo‘yishning yangi istiqbolli yo‘nalishlarini, bashoratlashning ilg‘or usullarini qo‘llagan holda chuqur tahlil qilish asosida asoslash va tanlash hamda ularning bajarilishini monitoring qilish;",
   list1_item4: "intensiv texnogenez hududlarida geologo-ekologik tadqiqotlar va xaritalash ishlarini olib borish usullarini ishlab chiqish;",
   list1_item5: "yer osti suvlari monitoringi va davlat kadastrini hamda yer osti suvlarining davlat hisobini yuritish;",
   list1_item6: "gidrogeologik va muhandislik-geologik tadqiqotlar usullari va tamoyillarini ishlab chiqish;",
   list1_item7: "yer osti suvlari konlarini qidirish, baholash va razvedka qilishning zamonaviy uslubrining oqilona kompleksini ishlab chiqish;",
   list1_item8: "yangi texnik vositalarni ishlab chiqish, yer osti suvlarini qidirish texnologiyalarini ishlab chiqish va ulardan oqilona foydalanish;",
   list1_item9: "chuchuk yer osti suvlari zahiralarini sun’iy ravishda to‘ldirish va ularni ifloslanishdan himoya qilish, gidromineral xom ashyoni qayta ishlash va ulardan foydalanish texnologiyalarini ishlab chiqish.",
   list2_name: "Institutning asosiy vazifalariga quyidagilar kiradi:",
   list2_item1: "o‘z vakolatlari doirasida geologiya-qidiruv ishlarini rivojlantirishning yillik, o‘rta muddatli va uzoq muddatli dasturlarini ishlab chiqish va shakllantirishda ishtirok etish;",
   list2_item2: "tizimli tahlil asosida aniq gidrogeologik ish obyektlari uchun bashoratli resurslarning ishonchliligi va obyektivligi to'g'risida xulosa chiqarish;",
   list2_item3: "ilmiy-tadqiqot, geoekologik, tematik, tajriba-konstruktorlik va nashriyot ishlarining ustuvor yo‘nalishlarini Davlat geologiya qo’mitasi bilan ishlab chiqiladi va kelishiladi;",
   list2_item4: "O‘zbekiston Respublikasi hududida yer osti suvlari konlarining shakllanishi va joylashish qonuniyatlarini o‘rganish bo‘yicha ishlarni amalga oshiradi;",
   list2_item5: "yer osti suvlari konlarini bashorat qilishni ularning bashoratlangan resurslarini baholagan holda amalga oshiradi va geologiya-qidiruv ishlarini keyingi yo‘nalishlar bo‘yicha ilmiy-uslubiy tavsiyalar ishlab chiqadi;",
   list2_item6: "chuqur tahlillar asosida, bashoratlashning ilg‘or uslublaridan, yangi istiqbolli hududlarda gidrogeologiya ishlarini yo‘lga qo‘yish, tasdiqlangan geologo-qidiruv ishlari dasturlari doirasida ularning bajarilishini nazorat qiladi;",
   list2_item7: "tizimli tahlil asosida geologo-qidiruv ishlari obyektlari uchun bashorat resurslarining ishonchliligi va obyektivligi to'g'risida xulosalar chiqaradi;",
   paragraph1: "Institut faoliyatining asosiy yo‘nalishlari bilan bog’liq ilmiy-tadqiqot, tajriba-uslubiy, tematik va boshqa ishlarning yo‘nalishlarini belgilovchi, loyiha-smeta hujjatlarini, amalga oshirilgan ishlar natijalari to‘g‘risidagi hisobotlarni va boshqa masalalarni ko‘rib chiquvchi Ilmiy Kengash - olimlardan, yuqori malakali mutaxassislar va institut olimlaridan tuziladi",
   list3_name: "Bajaradi:",
   list3_item1: "meliorativ gidrogeologiya, muhandislik-geologiyasi va gidrogeologiya sohasidagi tadqiqotlar;",
   list3_item2: "yer osti suvlarining monitoring;",
   list3_item3: "yer osti suvlarining ifloslanish va kamayib borish jarayonlarini o’rganish;",
   list3_item4: "foydali qazilmalar konlarini gidrogeologik va muhandislik-geologik sharoitlarini o’rganish;",
   list3_item5: "shahar va sanoat hududlarining ekologik sharoitlarini o’rganish;",
   list3_item6: "tog’ jinslarining fizik-mexanik xususiyatlarini aniqlash;",
   list3_item7: "topografik-geodeziya ishlarini olib borish va xaritalar chiqarish;",
   list3_item8: "yuridik va jismoniy shaxslarga pullik xizmatlar ko’rsatish.",
   list4_name: "Oxirgi yillardagi asosoiy ilmiy yutuqlari:",
   list4_item1: "Mavjud suv olish inshootlarida chuchuk yer osti suvlarining foydalanish zahiralarini ularning shakllanishning zamonaviy sharoitlarda qayta baholashga doir uslubiy talablar ishlab chiqilgan;",
   list4_item2: "Dala sharoitida aeratsiya zonasining lyos va shag'al jinslari orqali neft mahsulotlarining oqib o'tish xususiyatlari o'rganildi",
   list4_item3: "Yo'nalishli elektromagnit zondlash (YEMZ) uslubi ishlab chiqilgan;",
   list4_item4: "Markaziy Yevroosiyo boʻyicha xalqaro loyiha doirasida eng kuchli antropogen kuchlanishli boʻlgan Orol va Fargʻona mintaqalaridagi geologik muhitning hozirgi ekologik holati baholandi va transchegaraviy hududlar uchun 1:1000000 masshtabdagi geoekologik xaritalar tuzildi hamda Rossiya, Qirgʻiziston va Xitoy ishtirokida Markaziy Yevroosiyo xalqaro atlasiga nashr etish uchun taqdim etildi",
   list4_item5: "Farg'ona, Qashqadaryo va boshqalar bo’ycha yer osti mineral suvlarining yotishi va sifatini tavsiflovchi geofizik parametrlar va ko'rsatkichlar baholandi. strukturaviy-tektonik sharoitlarni turlashtirish va geofizik maydon parametrlarini taqsimlashda tizimli tahlil qilish tamoyiliga asoslangan artezian havzalari;",
   list4_item6: "Xavfli geologik jarayonlar (ko'chki jarayonlari) dan hududiy xavf haqida ogohlantirish uchun geoindikatorlar aniqlandi;",
   list4_item7: "XGJ monitoringini olib borish uslubiyati ishlab chiqildi;",
   list4_item8: "O‘zbekistonning yirik shaharlarining 1:25000 masshtabdagi 14 ta ekologik-geologik xaritalaridan iborat Atlas nashrga tayyorlandi;",
   list4_item9: "Qattiq foydali qazilmalar konlarini baholash va qidirish bosqichlarida gidrogeologik va muhandislik-geologik tadqiqotlarga qo‘yiladigan talablar ishlab chiqildi;",
   list4_item10: "Yer osti suvlarining davlat monitoringini o'tkazish uslubiyati ishlab chiqildi;",
   list4_item11: "Neft konlaridan uzoq muddatli va intensiv foydalanish sababli baholanadi Buxoro-Qarshi artezian havzasidagi yer osti suvlarining makro va mikrokomponent tarkibidagi o‘zgarishlari baholandi;",
   list4_item12: "Sanoat yer osti suvlaridan yod olish shartlarining texnik-iqtisodiy asoslarini tuzish va Kruk maydoniyada ularning zaxiralarini hisoblash;",
   list4_item13: "Yer osti suvlari konlarini shakllantirish uchun tabiiy kam suv manbalarining hududiy va mahalliylashtirilgan xususiyatlari baholandi;",
   list4_item14: "Yer osti suvlarining ifloslanishining o‘rta masshtabli xaritasini tuzish uslubiyatiga qo‘yiladigan talablar ishlab chiqildi; ",
   list4_item15: "ShEHMda suvli qatlamlarning gidrogeologik parametrlarini baholash bo'yicha uslubiy qo'llanmalar tuzildi.",
};

export default scientific