import Head from "next/head";

import Layout from "../../src/components/layout/layout";
import Engineering from "../../src/components/engineering/engineering";

export default function engineering() {
  return (
    <>
      <Head>
        <title>Hydroengeo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Engineering />
      </Layout>
    </>
  );
}
