import Head from "next/head";

import Layout from "../../src/components/layout/layout";
import FunctionsComponent from "../../src/components/functions/functions";

const Functions = () => {
  return (
    <>
      <Head>
        <title>Hydroengeo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FunctionsComponent />
      </Layout>
    </>
  );
};

export default Functions;
