import Head from "next/head";

import Layout from "../../src/components/layout/layout";
import Geoecology from "../../src/components/geoecology/geoecology";

export default function geoecology() {
  return (
    <>
      <Head>
        <title>Hydroengeo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Geoecology />
      </Layout>
    </>
  );
}
