import Head from "next/head";

import Layout from "../../src/components/layout/layout";
import Groundwater from "../../src/components/groundwater/groundwater";

export default function groundwater() {
  return (
    <>
      <Head>
        <title>Hydroengeo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Groundwater />
      </Layout>
    </>
  );
}
