import Head from "next/head";

import Layout from "../../src/components/layout/layout";
import Uran from "../../src/components/uran/uran";

const UranPage = () => {
  return (
    <>
      <Head>
        <title>Hydroengeo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Uran />
      </Layout>
    </>
  );
};

export default UranPage;
