import Head from "next/head";

import Layout from "../src/components/layout/layout";
import Financial from "../src/components/financial/financial";

export default function FinancialPage() {
  return (
    <>
      <Head>
        <title>Hydroengeo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Financial />
      </Layout>
    </>
  );
}
