import Head from "next/head";

import Layout from "../src/components/layout/layout";
import HomeAbout from "../src/components/home-about/home-about";
import HomeNews from "../src/components/home-news/home-news";
import International from "../src/components/international/international";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hydroengeo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="home-box">
          <HomeAbout />
          <HomeNews />
        </div>
        <International />
      </Layout>
    </>
  );
}
