import Head from "next/head";
import Image from "next/image";

import Layout from "../src/components/layout/layout";
import News from "../src/components/news/news";


export default function news() {
   return (
      <>
         <Head>
            <title>Hydroengeo</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <Layout>
            <News />
         </Layout>
      </>
   );
}
