import Head from "next/head";

import Layout from "../src/components/layout/layout";
import Normatives from "../src/components/Normatives/Normatives";

export default function normatives() {
  return (
    <>
      <Head>
        <title>Hydroengeo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Normatives />
      </Layout>
    </>
  );
}
