const history = {
  heading1: "HISTORY OF THE INSTITUTE OF HYDROGEOLOGY ",
  heading2: "AND ENGINEERING GEOLOGY",
  paragraph1: `Institute of Geology of the Academy of Sciences of the Uzbek SSR with the Department of Hydrogeology and Engineering Geology was organized in 1937 led first by B.I. Georgievsky,
  A.F. Slyadnev, B.A. Beder, A.I. Shevchenko, N.N. and from 1956 by A.S. Khasanov. In those years, many specialists of the Institute worked in various industry enterprises and universities of the Sredaztsvetmetrazvedka (Tashkent city)  -  L. Sandomirsky, N.I. Plotnikov, M.V. Syrovatko and others, Uglegazvedka, SAGU (TashGU)  -  M.M. Krylov, A.A. Khudaibergenov, R.V. Borodin and others, SazPI (ТаshPI) - V.L.Dmitriev, G.Mavlyanov, TashIITE- F.I.Voronov, TIIIMSKH - D.M.Kats, hydrogeological expedition, later the Uzbek hydrogeological trust - V.M. Fomin, 
  V.N. Tolokonnikov, R.Ya.Boiko, V.A. Geints, V.P. Volkov and many others. But the center of hydrogeology and engineering geology, where various scientific and production issues were discussed, was the Department of Hydrogeology and Engineering Geology of the Institute of Geology of the Academy of Sciences of the Uzbek SSR The period of organization of the Institute of Geology coincided with the wide scope of irrigation construction in Uzbekistan. In this regard, plans were made to develop irrigation in the Republic, expand irrigated and newly developed areas on the lands of the Hungry and Karshi steppes, the lower reaches of the Amu Darya, etc., which were reflected in grandiose water management measures and the expansion of irrigated areas. In this regard, the main research work of the Department of Hydrogeology and Engineering Geology was focused on the development of  irrigated lands reclamation. The Institute laid the foundation for two main areas of hydrogeological and engineering-geological research. 
`,
  paragraph2: `The period of organization of the Institute of Geology coincided with the wide scope of irrigation construction in Uzbekistan. In this regard, plans were made to develop irrigation in the Republic, expand irrigated and newly developed areas on the lands of the Hungry and Karshi steppes, the lower reaches of the Amu Darya, etc., which were reflected in grandiose water management measures and the expansion of irrigated areas. In this regard, the main research work of the Department of Hydrogeology and Engineering Geology was focused on the development of  irrigated lands reclamation. The Institute laid the foundation for two main areas of hydrogeological and engineering-geological research. `,
  paragraph3: `The first is the development of hydrogeological and engineering-geological zoning in relation to the needs of irrigated agriculture. In this direction, research work was carried out in the Ferghana Valley, the Hungry Steppe, the lower reaches of the Amu Darya, the Bukhara oasis and other areas of irrigated agriculture of the Republic. O.K. Lange, M.A. Schmidt, B.M. Georgievsky, 
  G.A. Mavlyanov, M.M. Krylov and others participated in the development of zoning. Under the leadership of  O.K. Lange, as a result of research conducted in the Ferghana Valley, the first map of the of groundwater depth and mineralization was compiled. The first works on hydrogeology appeared, in particular, on the methodology for hydrcogeological maps compiling which served as the beginning of hydrogeological zoning, that became one of the important directions for the Institute of Geology (N.A. Kenesarin, M.M. Krylov). The first map of groundwater depths and hydroisohypses of Uzbekistan (the Hungry Steppe) was compiled at a 10- vers scale in 1926-1928. 
`,
  paragraph4: `The second direction of hydrogeological and engineering-geological research, which received rapid and deep development, was the study of the groundwater regime and balance in irrigated areas in order to justify reclamation measures to combat soil salinization. Previous studies have shown that as a result of land irrigation the groundwater level quickly rises above the critical depth, and the land is exposed to salinization. The term " groundwater critical depth " was introduced into science by M.M. Krylov and for the territory of Uzbekistan it is 3,5 m, above which the process of land salinization begins. In this regard, the regime and dynamics of the groundwater balance in the Hungry Steppe, one of the best and most promising regions of Uzbekistan, were studied in detail. The need for differentiated reclamation measures concerning irrigated lands for the artificial regulation of the groundwater regime has been established. There was an acute question about the construction of drainage on irrigated lands, a scientifically based solution of which could only be achieved by studying the groundwater regime and balance (M.M. Krylov, A.F. Slyadnev, 
  N.N. Khodzhibaev, A. S.Khasanov). Two directions of scientific research of the Institute of Geology in the field of groundwater study were the basis for the emergence in Uzbekistan of a new direction of hydrogeological science - meliorative hydrogeology.
  New approach to land cultivation and improvement of their condition has been practically formulated. 
`,
  paragraph5: `As a result of many years of research by a team of scientists from the Department of Hydrogeology and Engineering Geology, the most important and priority tasks of meliorative hydrogeology have been identified:`,
  tasks1: `1. Hydrogeological and reclamation zoning of Uzbekistan as the basis for irrigation and economic planning and hydromodular zoning of existing and prospective irrigation areas. `,
  tasks2: `2. Development of groundwater regime genetic types classification for the reclamation control service and hydrogeological information in the management of irrigation systems. `,
  tasks3: `3. Studying the water and water-salt balance of existing and prospective irrigation systems to assess the effectiveness of land reclamation measures and justify their design as well as to predict the groundwater regime. `,
  tasks4: `4. Development of methods for predicting the groundwater regime, which is necessary when designing reclamation measures, in particular, drainage for artificial regulation of groundwater table especially on lands subject to salinization. `,
  tasks5: `5. Assessment of groundwater reserves as an additional source of irrigation and ways to use them. `,
  tasks6: `6. Identification of the geological and hydrogeological conditions for the use of vertical and horizontal drainage and its structures, as well as the determination of necessary parameters for their design. `,
  paragraph6: `These researches until 1960 were conducted  by, M.A. Schmidt, B.M. Georgievsky, N.A. Kenesarin, M.M. Krylov, A.F. Slyadnev, A.I. .Kats, N.N.Khodzhibaev, A.S.Khasanov, S.Sh.Mirzaev, A.N.Sultankhodzhaev and others. `,
  paragraph7: `In January 1960  the Institute of Hydrogeology and Engineering Geology (GIDROINGEO) was founded on the basis of Decree No. 737 of the Council of Ministers of the Uzbek SSR dated September 29, 1959 “On the organization within the system of the Academy of Sciences of Uzbekistan of the Institute of Hydrogeology and Engineering Geology (GIDROINGEO)”, which was a significant event for a large team of hydrogeologists and engineers-geologists of Uzbekistan. The first leaders of the institute were: director -  doctor of geological and mineralogical sciences professor G.A. Mavlyanov, deputy director for science - candidate of geological and mineralogical sciences N.A. Kenesarin. `,
  paragraph8: `The Institute consisted of four laboratories (regional hydrogeology, mineral waters and hydrochemistry, reclamation hydrogeology, engineering geology) and the Golodnostepskaya hydrogeological scientific-research station. 63 people worked in the staff of the Institute including two doctors and four condidates of sciences. 
  The main directions in the research work of the Institute were determined: the study of the patterns of groundwater formation, the identification of groundwater resources and industrial brines for their use in the national economy, the development of the main issues of reclamation hydrogeology of irrigated agricultural areas; study of regularities of loess rocks and their engineering-geological properties; improvement of methods and techniques of hydrogeological works, analysis of their economics and efficiency; scientific substantiation of hydrogeological and engineering-geological studies; development of individual practical proposals for the prompt solution of issues of the national economy by production organizations; coordination of research and thematic work on hydrogeology and engineering geology of the arid zone. 
`,
  paragraph9: `In 1961 the Institute already had seven laboratories: groundwater resources, arid hydrogeology, reclamation hydrogeology, engineering geology, landslide processes and phenomena, regional hydrogeology, chemical identification and Golodnostepskaya hydrogeological scientific-research station. In 1963 the Institute was transferred to the system of the Ministry of Geology. At that time, 223 people worked at the Institute, including two doctors and 18 candidates of sciences. `,
  paragraph10: `On June 4, 1971, on the basis of the GIDROINGEO Institute and the Uzbekhydrogeology trust, the Uzbekhydrogeology Research and Production Association was established. The Institute expanded – there where 9 departments with 26 laboratories, an experimental methodological party, an examination party, advanced training courses. The number of employees increased to 385 people, including five doctors and 54 candidates of sciences. The following departments worked: regional hydrogeological and engineering-geological research, resources, methods of exploration and protection of groundwater, hydrogeology of the noosphere, deep waters, engineering geodynamics, modeling of hydrogeological processes, etc.). `,
  paragraph11: `Field trips were organized in the expeditions of the association, where specialists got acquainted with the field work of the expeditions. At their request, tourist excursions to the cities of Samarkand, Kokand, Bukhara and Khiva were carried out. The courses were attended  by specialists from Siberia, the Far East, Ukraine, the Baltic states and other regions. The HIDROINGEO Institute provided methodological guidance for hydrogeological and engineering-geological studies in the arid zone. `,
  paragraph12: `On its basis, there was a Special Council for the defense of doctoral and master's theses. More than 150 theses were defended at this Council. `,
  paragraph13: `On the basis of the Decree of the President of the Republic of Uzbekistan No. PP-568 "On measures to improve the organization of geological work and the activities of the State Committee of the Republic of Uzbekistan on Geology and Mineral Resources" and on the basis of the order of the State Committee of the Republic of Uzbekistan on Geology and Mineral Resources No. 11 dated January 25, 2007 the Institute is a structural subdivision of the State Committee for Geology of the Republic of Uzbekistan. `,
  directions: `To date, the Institute is working in the following areas:`,
  directions1: `- Scientific and methodological support for prospecting, exploration and evaluation of groundwater reserves, protection of groundwater from depletion and their rational use, regional hydrogeological studies. `,
  directions2: `- Prevention and forecast of hazardous geological processes occurrence, justification of the stability of mine workings of solid minerals deposits and other engineering and technical facilities.  `,
  directions3: `- Geoecological research and mapping, identification of patterns and forecast of the evolution of the geological environment components under the influence of natural and technogenic factors in order to assess the current state and improve the environmental situation in the region. `,
  directions4: `- Providing and improving the scientific and technical base of research work allowing to increase the productivity, efficiency and reliability of the results obtained: hydrogeophysical, remote sensing of the earth, GIS technologies, development work, mathematical modeling.`,
  directions5: `- Maintenance of State cadastres: water (in terms of groundwater), protected natural areas (PNA) and hazardous geological processes (HGP) of the Republic of Uzbekistan. Today, the Institute employs 181 employees, including 5 doctors of science, 22 candidates of science and 112 specialists with higher education.`,
};

export default history;
