const scientific = {
   heading: "Scientific activity",
   list1_name: "The main directions of research of the Institute:",
   list1_item1: "substantiation and implementation of priority areas of research, geo-environmental, thematic work and laboratory and technological research to assess the hydromineral potential of the Republic, the allocation of promising areas of groundwater distribution with an assessment of forecast resources for setting prospecting works;",
   list1_item2: "improvement of methods for forecasting, prospecting, evaluation and exploration of groundwater deposits;",
   list1_item3: "substantiation and selection on the basis of in-depth analysis, using advanced forecasting methods, new promising areas for setting up geological exploration for groundwater and monitoring their implementation within the framework of approved exploration programs;",
   list1_item4: "development of methods for conducting geological and environmental studies and mapping in areas of intensive technogenesis;",
   list1_item5: "maintaining groundwater monitoring and state cadastres and state accounting of groundwater;",
   list1_item6: "development of methods and principles of hydrogeological and engineering-geological studies;",
   list1_item7: "development of a rational complex of modern methods of prospecting, evaluation and exploration of groundwater deposits;",
   list1_item8: "development of new technical means, development of groundwater exploration technologies and their rational use;",
   list1_item9: "development of technologies for artificial replenishment of fresh groundwater reserves and their protection from pollution, processing of hydromineral raw materials and their use. ",
   list2_name: "The main tasks of the Institute are: ",
   list2_item1: "participation in the development and formation of annual, medium-term and long-term programs for the development of geological exploration within its competence;",
   list2_item2: "issuance, on the basis of a system analysis, of a conclusion on the reliability and objectivity of predictive resources for specific objects of hydrogeological work;",
   list2_item3: "development and coordination with the State Commity of Geology the priority areas of research, geoecological, thematic, experimental design and publishing work; ",
   list2_item4: "work on the study of the groundwater deposits formation and patterns of placement on the territory of the Republic of Uzbekistan;",
   list2_item5: "forecasting of groundwater deposits with an assessment of their predictive resources and the development of scientific and methodological recommendations for the further direction of geological exploration;",
   list2_item6: "forecasting, based on in-depth analysis, using advanced forecasting methods, new promising areas for setting up hydrogeological work, monitoring their implementation within the framework of approved exploration programs;",
   list2_item7: "issuance, based on system analysis, conclusions on the reliability and objectivity of forecast resources for hydrogeological exploration objects; ",
   paragraph1: "The Academic Council, formed from scientists, highly qualified specialists and scientists of the Institute, determines the directions of research, experimental, methodological, thematic and other work, considers design estimates, reports on the results of work carried out and other issues related to the main activities of the Institute. ",
   list3_name: "The laboratory carries out:",
   list3_item1: "research in the field of ameliorative hydrogeology, engineering geology and geohydrology;",
   list3_item2: "groundwater monitoring;",
   list3_item3: "study of process of groundwater reserves pollution and depletion;",
   list3_item4: "study of hydrogeological and engineering-geological conditions of mineral deposits;",
   list3_item5: "study of ecological conditions of cities and industrial zones;",
   list3_item6: "determination of physical and mechanical properties of rocks;",
   list3_item7: "conducting topographic and geodetic works and issuing maps;",
   list3_item8: "provides paid services to legal entities and individuals.",
   list4_name: "Main scientific achievements in recent years: ",
   list4_item1: "Methodological requirements have been developed for the reassessment of operational reserves of fresh groundwater at existing water intakes in the current conditions of their formation;",
   list4_item2: "The features of oil products seepage through loess and pebble rocks of the aeration zone in field conditions were studied;",
   list4_item3: "A method of directional electromagnetic sounding (DEMS) has been developed;",
   list4_item4: "The current ecological state of the geological environment was assessed and geoecological maps were compiled at a scale of 1:1000000 for transboundary territories with the most intense anthropogenic load of the Aral and Fergana regions within the framework of the International Project on Central Eurasia and submitted for publication to the international atlas of Central Eurasia with the participation of Russia, Kyrgyzstan and China;",
   list4_item5: "The geophysical parameters and indicators characterizing the occurrence and quality of mineral groundwater in the Fergana, Kashkadarya and other artesian basins are estimated based on the principle of structural-tectonic conditions typification and system analysis in the distribution of geophysical field parameters",
   list4_item6: "Geoindicators for the warning about areal danger from LSP (landslide processes) have been determined;",
   list4_item7: "A methodology for conducting monitoring of the LSP has been developed;",
   list4_item8: "Prepared for publication of the Atlas consisting of 14 ecological and geological maps of large cities of Uzbekistan at a scale of 1: 25000;",
   list4_item9: "Requirements for hydrogeological and engineering-geological studies of solid mineral deposits at the stages of evaluation and exploration have been developed;",
   list4_item10: "A methodology for conducting groundwater state monitoring has been developed;",
   list4_item11: "Changes in the macro- and microcomponent composition of groundwater in the Bukhara-Karshi artesian basin due to long-term and intensive exploitation of oil fields were assessed;",
   list4_item12: "Drawing up a feasibility study of conditions for the extraction of iodine from industrial groundwater and calculation of their reserves at the Kruk site;",
   list4_item13: "The territorial and localized features of natural low water in the sources of groundwater deposits formation were assessed;",
   list4_item14: "Requirements for the methodology of compiling a medium-scale map of groundwater pollution have been developed;",
   list4_item15: "Compiled methodological manuals for assessing the hydrogeological parameters of aquifers on a PC. ",
};

export default scientific